### ISSUE TITLE
Weather App - initial screens

### ISSUE THREAD

**Issue by narefyev91** [liubovvention/VTestApp#1]
The weather app will consist of two screens:

The first screen will display a list of cities. Each item in the list will display the name of the city, and some basic weather information (temperature, conditions).

The second screen will display additional details such as humidity, wind speed, and minimum/maximum temperatures for the day.
The app will use current weather data provided by the Open Weather Map API - https://openweathermap.org/api

Example:
![WeatherApp (1)](https://github.com/user-attachments/assets/eb0c8e5d-7e0b-4de8-a08d-a7ecfdb59a94)

**Comment by liubovvention** [comment]
Got it, thanks
________________________________
